# Generated by Django 2.1.5 on 2019-05-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=5000)),
                ('pdf', models.FileField(blank=True, max_length=1000, upload_to='boletines/')),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('logo', models.ImageField(null=True, upload_to='centros/')),
                ('direccion', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=175)),
                ('descripcion', models.CharField(max_length=5000)),
                ('fecha', models.DateField()),
                ('centro', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='acrp.Centro')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRemitente', models.CharField(max_length=75)),
                ('correoRemitente', models.EmailField(max_length=75)),
                ('telefonoRemitente', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('resumenCV', models.CharField(default='cantidad de cosas que sabe hacer', max_length=500)),
                ('activo', models.BooleanField()),
                ('foto', models.ImageField(null=True, upload_to='members/')),
                ('boletines', models.ManyToManyField(blank=True, related_name='autores', to='acrp.Boletin')),
                ('centro', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='acrp.Centro')),
                ('mensajes', models.ManyToManyField(blank=True, related_name='miembros', to='acrp.Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(null=True, upload_to='noticias/')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=5000)),
                ('pdf', models.FileField(blank=True, max_length=1000, upload_to='')),
                ('miembros', models.ManyToManyField(blank=True, related_name='proyectos', to='acrp.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=5000)),
                ('pdf', models.FileField(blank=True, max_length=1000, upload_to='publicaciones/')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='publicaciones',
            field=models.ManyToManyField(blank=True, related_name='autores', to='acrp.Publicacion'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to=settings.AUTH_USER_MODEL),
        ),
    ]
