# Generated by Django 2.1.5 on 2019-01-15 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('activo', models.BooleanField()),
                ('foto', models.ImageField(null=True, upload_to='members/')),
                ('centro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acrp.Centro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('pdf', models.FileField(blank=True, max_length=1000, upload_to='')),
                ('miembros', models.ManyToManyField(blank=True, related_name='proyectos', to='acrp.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('pdf', models.FileField(blank=True, max_length=1000, upload_to='')),
                ('autores', models.ManyToManyField(blank=True, related_name='publicaciones', to='acrp.Miembro')),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
