# Generated by Django 2.1.5 on 2019-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrp', '0002_auto_20190515_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.CharField(default='miembro', max_length=50),
            preserve_default=False,
        ),
    ]
