# Generated by Django 2.1.5 on 2019-01-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrp', '0003_centro_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('categoria', models.CharField(max_length=150)),
                ('direccion', models.FileField(blank=True, max_length=1000, upload_to='')),
                ('fecha', models.DateField()),
                ('centro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acrp.Centro')),
            ],
        ),
    ]
