# Generated by Django 2.1.5 on 2019-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrp', '0004_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(max_length=175),
        ),
    ]
