# Generated by Django 2.1.5 on 2019-01-15 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrp', '0005_auto_20190115_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='resumenCV',
            field=models.CharField(default='cantidad de cosas que sabe hacer', max_length=500),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to=settings.AUTH_USER_MODEL),
        ),
    ]
